# Copyright 2016 Casey Jaymes

# This file is part of PySCAP.
#
# PySCAP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PySCAP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PySCAP.  If not, see <http://www.gnu.org/licenses/>.
TAG_MAP = {
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_test': {'class': 'AccessTokenTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_test': {'class': 'ActiveDirectory57TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_test': {'class': 'ActiveDirectoryTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_test': {'class': 'AuditEventPolicySubcategoriesTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_test': {'class': 'AuditEventPolicyTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_test': {'class': 'CmdletTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_test': {'class': 'DNSCacheTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_test': {'class': 'FileAuditedPermissions53TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_test': {'class': 'FileAuditedpermissionsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_test': {'class': 'FileEffectiveRights53TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_test': {'class': 'FileEffectiveRightsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_test': {'class': 'FileTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_test': {'class': 'GroupSIDTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_test': {'class': 'GroupTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_test': {'class': 'InterfaceTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_test': {'class': 'LicenseTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_test': {'class': 'LockoutPolicyTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_test': {'class': 'MetabaseTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_test': {'class': 'NTUserTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_test': {'class': 'PasswordPolicyTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_test': {'class': 'PEHeaderTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_test': {'class': 'PortTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_test': {'class': 'PrinterEffectiveRightsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_test': {'class': 'Process58TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_test': {'class': 'ProcessTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_test': {'class': 'RegistryTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_test': {'class': 'RegKeyAuditedPermissions53TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_test': {'class': 'RegKeyAuditedPermissionsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_test': {'class': 'RegKeyEffectiveRights53TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_test': {'class': 'RegKeyEffectiveRightsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_test': {'class': 'ServiceEffectiveRightsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_test': {'class': 'ServiceTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_test': {'class': 'SharedResourceAuditedPermissionsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_test': {'class': 'SharedResourceEffectiveRightsTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_test': {'class': 'SharedResourceTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_test': {'class': 'SIDSIDTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_test': {'class': 'SIDTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_test': {'class': 'SystemMetricTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_test': {'class': 'UACTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_test': {'class': 'UserRightTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_test': {'class': 'UserSID55TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_test': {'class': 'UserSIDTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_test': {'class': 'UserTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_test': {'class': 'VolumeTestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_test': {'class': 'WMI57TestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_test': {'class': 'WMITestType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_test': {'class': 'WUAUpdateSearcherTestType'},

    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_object': {'class': 'AccessTokenObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_object': {'class': 'ActiveDirectory57ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_object': {'class': 'ActiveDirectoryObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_object': {'class': 'AuditEventPolicySubcategoriesObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_object': {'class': 'AuditEventPolicyObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_object': {'class': 'CmdletObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_object': {'class': 'DNSCacheObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_object': {'class': 'FileAuditedPermissions53ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_object': {'class': 'FileAuditedpermissionsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_object': {'class': 'FileEffectiveRights53ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_object': {'class': 'FileEffectiveRightsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_object': {'class': 'FileObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_object': {'class': 'GroupSIDObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_object': {'class': 'GroupObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_object': {'class': 'InterfaceObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_object': {'class': 'LicenseObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_object': {'class': 'LockoutPolicyObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_object': {'class': 'MetabaseObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_object': {'class': 'NTUserObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_object': {'class': 'PasswordPolicyObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_object': {'class': 'PEHeaderObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_object': {'class': 'PortObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_object': {'class': 'PrinterEffectiveRightsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_object': {'class': 'Process58ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_object': {'class': 'ProcessObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_object': {'class': 'RegistryObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_object': {'class': 'RegKeyAuditedPermissions53ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_object': {'class': 'RegKeyAuditedPermissionsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_object': {'class': 'RegKeyEffectiveRights53ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_object': {'class': 'RegKeyEffectiveRightsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_object': {'class': 'ServiceEffectiveRightsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_object': {'class': 'ServiceObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_object': {'class': 'SharedResourceAuditedPermissionsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_object': {'class': 'SharedResourceEffectiveRightsObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_object': {'class': 'SharedResourceObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_object': {'class': 'SIDSIDObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_object': {'class': 'SIDObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_object': {'class': 'SystemMetricObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_object': {'class': 'UACObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_object': {'class': 'UserRightObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_object': {'class': 'UserSID55ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_object': {'class': 'UserSIDObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_object': {'class': 'UserObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_object': {'class': 'VolumeObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_object': {'class': 'WMI57ObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_object': {'class': 'WMIObjectType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_object': {'class': 'WUAUpdateSearcherObjectType'},

    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}accesstoken_state': {'class': 'AccessTokenStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory57_state': {'class': 'ActiveDirectory57StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}activedirectory_state': {'class': 'ActiveDirectoryStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicysubcategories_state': {'class': 'AuditEventPolicySubcategoriesStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}auditeventpolicy_state': {'class': 'AuditEventPolicyStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}cmdlet_state': {'class': 'CmdletStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}dnscache_state': {'class': 'DNSCacheStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions53_state': {'class': 'FileAuditedPermissions53StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileauditedpermissions_state': {'class': 'FileAuditedpermissionsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights53_state': {'class': 'FileEffectiveRights53StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}fileeffectiverights_state': {'class': 'FileEffectiveRightsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}file_state': {'class': 'FileStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_sid_state': {'class': 'GroupSIDStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}group_state': {'class': 'GroupStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}interface_state': {'class': 'InterfaceStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}license_state': {'class': 'LicenseStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}lockoutpolicy_state': {'class': 'LockoutPolicyStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}metabase_state': {'class': 'MetabaseStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}ntuser_state': {'class': 'NTUserStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}passwordpolicy_state': {'class': 'PasswordPolicyStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}peheader_state': {'class': 'PEHeaderStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}port_state': {'class': 'PortStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}printereffectiverights_state': {'class': 'PrinterEffectiveRightsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process58_state': {'class': 'Process58StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}process_state': {'class': 'ProcessStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}registry_state': {'class': 'RegistryStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions53_state': {'class': 'RegKeyAuditedPermissions53StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyauditedpermissions_state': {'class': 'RegKeyAuditedPermissionsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights53_state': {'class': 'RegKeyEffectiveRights53StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}regkeyeffectiverights_state': {'class': 'RegKeyEffectiveRightsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}serviceeffectiverights_state': {'class': 'ServiceEffectiveRightsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}service_state': {'class': 'ServiceStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceauditedpermissions_state': {'class': 'SharedResourceAuditedPermissionsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresourceeffectiverights_state': {'class': 'SharedResourceEffectiveRightsStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sharedresource_state': {'class': 'SharedResourceStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_sid_state': {'class': 'SIDSIDStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}sid_state': {'class': 'SIDStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}systemmetric_state': {'class': 'SystemMetricStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}uac_state': {'class': 'UACStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}userright_state': {'class': 'UserRightStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid55_state': {'class': 'UserSID55StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_sid_state': {'class': 'UserSIDStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}user_state': {'class': 'UserStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}volume_state': {'class': 'VolumeStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi57_state': {'class': 'WMI57StateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wmi_state': {'class': 'WMIStateType'},
    '{http://oval.mitre.org/XMLSchema/oval-definitions-5#windows}wuaupdatesearcher_state': {'class': 'WUAUpdateSearcherStateType'},
}
